spring:
  profiles:
    active: local
    include:
      - common
    group:
      local:
        - common
      prod:
        - common

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:postgresql://localhost:3306/pharmacy-finder-maria-db
    username: user
    password: pharmacy_finder_password
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: prod