version: '3.8'
services:
  pharmacy-finder-redis:
    container_name: pharmacy-finder-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: deadwhale/pharmacy-finder-redis
    ports:
      - "6379:6379"
  pharmacy-finder-maria-db:
    container_name: pharmacy-finder-maria-db
    build:
      dockerfile: Dockerfile
      context: ./database
    image: deadwhale/pharmacy-finder-maria-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pharmacy_finder_maria_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"
